//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthTracker.Infrastructure.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Food Group of this name already exists.
        /// </summary>
        public static string Error_FoodGroup_Exists {
            get {
                return ResourceManager.GetString("Error_FoodGroup_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Food Item with this name already exists..
        /// </summary>
        public static string Error_FoodItem_Exists {
            get {
                return ResourceManager.GetString("Error_FoodItem_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Meal Template with this name already exists..
        /// </summary>
        public static string Error_MealTemplate_Exists {
            get {
                return ResourceManager.GetString("Error_MealTemplate_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Meal Type by this name already exists.
        /// </summary>
        public static string Error_MealType_Exists {
            get {
                return ResourceManager.GetString("Error_MealType_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories must be greater than or equal to zero..
        /// </summary>
        public static string Error_Negative_Calories {
            get {
                return ResourceManager.GetString("Error_Negative_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one food group must be specified..
        /// </summary>
        public static string Error_No_FoodGroups {
            get {
                return ResourceManager.GetString("Error_No_FoodGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A meal must consist of at least one item of food..
        /// </summary>
        public static string Error_No_FoodItems {
            get {
                return ResourceManager.GetString("Error_No_FoodItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A time must be supplied for the meal..
        /// </summary>
        public static string Error_No_MealTime {
            get {
                return ResourceManager.GetString("Error_No_MealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of meal must be specified..
        /// </summary>
        public static string Error_No_MealType {
            get {
                return ResourceManager.GetString("Error_No_MealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be specified..
        /// </summary>
        public static string Error_No_Name {
            get {
                return ResourceManager.GetString("Error_No_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity must be greater than zero..
        /// </summary>
        public static string Error_No_Quantity {
            get {
                return ResourceManager.GetString("Error_No_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serving item must be specified..
        /// </summary>
        public static string Error_No_ServingItem {
            get {
                return ResourceManager.GetString("Error_No_ServingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this food group will not be saved.  Are you sure you want to close?.
        /// </summary>
        public static string Question_FoodGroup_Close {
            get {
                return ResourceManager.GetString("Question_FoodGroup_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this food group cannot be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Question_FoodGroup_Delete {
            get {
                return ResourceManager.GetString("Question_FoodGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes to this food group?.
        /// </summary>
        public static string Question_FoodGroup_Save {
            get {
                return ResourceManager.GetString("Question_FoodGroup_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this food item will not be saved.  Are you sure you want to close?.
        /// </summary>
        public static string Question_FoodItem_Close {
            get {
                return ResourceManager.GetString("Question_FoodItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this food item cannot be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Question_FoodItem_Delete {
            get {
                return ResourceManager.GetString("Question_FoodItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes to this food item?.
        /// </summary>
        public static string Question_FoodItem_Save {
            get {
                return ResourceManager.GetString("Question_FoodItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the meal will not be saved.  Are you sure you want to close?.
        /// </summary>
        public static string Question_Meal_Close {
            get {
                return ResourceManager.GetString("Question_Meal_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this meal cannot be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Question_Meal_Delete {
            get {
                return ResourceManager.GetString("Question_Meal_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes to this meal?.
        /// </summary>
        public static string Question_Meal_Save {
            get {
                return ResourceManager.GetString("Question_Meal_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this meal template will not be saved.  Are you sure you want to close?.
        /// </summary>
        public static string Question_MealTemplate_Close {
            get {
                return ResourceManager.GetString("Question_MealTemplate_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this meal template cannot be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Question_MealTemplate_Delete {
            get {
                return ResourceManager.GetString("Question_MealTemplate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes to this meal template?.
        /// </summary>
        public static string Question_MealTemplate_Save {
            get {
                return ResourceManager.GetString("Question_MealTemplate_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this meal type will not be saved.  Are you sure you want to close?.
        /// </summary>
        public static string Question_MealType_Close {
            get {
                return ResourceManager.GetString("Question_MealType_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this meal type cannot be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Question_MealType_Delete {
            get {
                return ResourceManager.GetString("Question_MealType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes to this meal type?.
        /// </summary>
        public static string Question_MealType_Save {
            get {
                return ResourceManager.GetString("Question_MealType_Save", resourceCulture);
            }
        }
    }
}
